# Generated by Django 5.1.15 on 2026-04-29 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0034_project_annotator_evaluation_enabled"),
        ("tasks", "0061_task_project_file_upload_idx_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("random", "随机切割"),
                            ("stratified", "分层切割"),
                            ("timeseries", "时间序列切割"),
                            ("manual", "手动指定"),
                        ],
                        default="random",
                        max_length=32,
                        verbose_name="切割类型",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="配置参数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "total_tasks",
                    models.IntegerField(default=0, verbose_name="总任务数"),
                ),
                (
                    "train_tasks",
                    models.IntegerField(default=0, verbose_name="训练集任务数"),
                ),
                (
                    "test_tasks",
                    models.IntegerField(default=0, verbose_name="测试集任务数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_splits",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据集切割",
                "verbose_name_plural": "数据集切割",
                "db_table": "model_testing_dataset_split",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "model_versions",
                    models.JSONField(default=list, verbose_name="模型版本列表"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "summary_metrics",
                    models.JSONField(default=dict, verbose_name="汇总指标"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="model_testing.datasetsplit",
                        verbose_name="切割配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型评估",
                "verbose_name_plural": "模型评估",
                "db_table": "model_testing_model_evaluation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("csv", "CSV"),
                        ],
                        max_length=16,
                        verbose_name="格式",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evaluation_reports/",
                        verbose_name="文件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="model_testing.modelevaluation",
                        verbose_name="评估记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "评估报告",
                "verbose_name_plural": "评估报告",
                "db_table": "model_testing_evaluation_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatasetSplitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[("train", "训练集"), ("test", "测试集")],
                        max_length=16,
                        verbose_name="分组",
                    ),
                ),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="model_testing.datasetsplit",
                        verbose_name="切割配置",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_items",
                        to="tasks.task",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "切割项",
                "verbose_name_plural": "切割项",
                "db_table": "model_testing_dataset_split_item",
                "indexes": [
                    models.Index(
                        fields=["split", "group"], name="model_testi_split_i_5111a7_idx"
                    )
                ],
                "unique_together": {("split", "task")},
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(max_length=255, verbose_name="模型版本"),
                ),
                ("metrics", models.JSONField(default=dict, verbose_name="整体指标")),
                (
                    "per_class_metrics",
                    models.JSONField(default=dict, verbose_name="分类别指标"),
                ),
                (
                    "confusion_matrix",
                    models.JSONField(default=list, verbose_name="混淆矩阵"),
                ),
                (
                    "error_samples",
                    models.JSONField(default=list, verbose_name="错误样本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="model_testing.modelevaluation",
                        verbose_name="评估记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "评估结果",
                "verbose_name_plural": "评估结果",
                "db_table": "model_testing_evaluation_result",
                "unique_together": {("evaluation", "model_version")},
            },
        ),
    ]
